trigger: none

pool:
  name: Default

steps:

- script: npm ci --legacy-peer-deps
  displayName: Install Dependencies

- script: npm run build
  displayName: Build Vite App

- script: |
    robocopy dist E:\testDeployment\dist /E /MIR
    exit 0
  displayName: Deploy Dist Folder